export const ORDERS_CREATE_REQUEST = 'ORDERS_CREATE_REQUEST';
export const ORDERS_CREATE_SUCCESS = 'ORDERS_CREATE_SUCCESS';
export const ORDERS_CREATE_FAIL = 'ORDERS_CREATE_FAIL';

export const ORDERS_DETAILS_REQUEST = 'ORDERS_DETAILS_REQUEST';
export const ORDERS_DETAILS_SUCCESS = 'ORDERS_DETAILS_SUCCESS';
export const ORDERS_DETAILS_FAIL = 'ORDERS_DETAILS_FAIL';
