export const ORDERS_CREATE_REQUEST = 'ORDERS_CREATE_REQUEST';
export const ORDERS_CREATE_SUCCESS = 'ORDERS_CREATE_SUCCESS';
export const ORDERS_CREATE_FAIL = 'ORDERS_CREATE_FAIL';

export const ORDERS_DETAILS_REQUEST = 'ORDERS_DETAILS_REQUEST';
export const ORDERS_DETAILS_SUCCESS = 'ORDERS_DETAILS_SUCCESS';
export const ORDERS_DETAILS_FAIL = 'ORDERS_DETAILS_FAIL';

export const ORDERS_PAY_REQUEST = 'ORDERS_PAY_REQUEST';
export const ORDERS_PAY_SUCCESS = 'ORDERS_PAY_SUCCESS';
export const ORDERS_PAY_FAIL = 'ORDERS_PAY_FAIL';
export const ORDERS_PAY_RESET = 'ORDERS_PAY_RESET';

export const ORDERS_LOGGED_IN_USERS_REQUEST = 'ORDERS_LOGGED_IN_USERS_REQUEST';
export const ORDERS_LOGGED_IN_USERS_SUCCESS = 'ORDERS_LOGGED_IN_USERS_SUCCESS';
export const ORDERS_LOGGED_IN_USERS_FAIL = 'ORDERS_LOGGED_IN_USERS_FAIL';
export const ORDERS_LOGGED_IN_USERS_RESET = 'ORDERS_LOGGED_IN_USERS_RESET';

export const ORDERS_GET_REQUEST = 'ORDERS_GET_REQUEST';
export const ORDERS_GET_SUCCESS = 'ORDERS_GET_SUCCESS';
export const ORDERS_GET_FAIL = 'ORDERS_GET_FAIL';

export const ORDERS_DELIVER_REQUEST = 'ORDERS_DELIVER_REQUEST';
export const ORDERS_DELIVER_SUCCESS = 'ORDERS_DELIVER_SUCCESS';
export const ORDERS_DELIVER_FAIL = 'ORDERS_DELIVER_FAIL';
export const ORDERS_DELIVER_RESET = 'ORDERS_DELIVER_RESET';
