export const ORDERS_CREATE_REQUEST = 'ORDERS_CREATE_REQUEST';
export const ORDERS_CREATE_SUCCESS = 'ORDERS_CREATE_SUCCESS';
export const ORDERS_CREATE_FAIL = 'ORDERS_CREATE_FAIL';

export const ORDERS_DETAILS_REQUEST = 'ORDERS_DETAILS_REQUEST';
export const ORDERS_DETAILS_SUCCESS = 'ORDERS_DETAILS_SUCCESS';
export const ORDERS_DETAILS_FAIL = 'ORDERS_DETAILS_FAIL';

export const ORDERS_PAY_REQUEST = 'ORDERS_PAY_REQUEST';
export const ORDERS_PAY_SUCCESS = 'ORDERS_PAY_SUCCESS';
export const ORDERS_PAY_FAIL = 'ORDERS_PAY_FAIL';
export const ORDERS_PAY_RESET = 'ORDERS_PAY_RESET';
